### ISSUE TITLE
Syntax error on moduleultra.

### ISSUE THREAD

**Issue by kohei-108** [MetaSUB/MetaSUB_CAP#26]
After installing DataSuper, PackageMega, and ModuleUltra, I ran the following command.

`moduleultra init`

The following error occurred.

```
(py35) [t15089ki@bias5-login tools]$ moduleultra init
Traceback (most recent call last):
  File "/home/t15089ki/miniconda3/envs/py35/bin/moduleultra", line 11, in <module>
    load_entry_point('ModuleUltra', 'console_scripts', 'moduleultra')()
  File "/home/t15089ki/miniconda3/envs/py35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/t15089ki/miniconda3/envs/py35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "/home/t15089ki/miniconda3/envs/py35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/home/t15089ki/miniconda3/envs/py35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/mnt/gpfsA/home/t15089ki/tools/ModuleUltra/moduleultra/__init__.py", line 3, in <module>
    from .module_ultra_config import *
  File "/mnt/gpfsA/home/t15089ki/tools/ModuleUltra/moduleultra/module_ultra_config.py", line 6, in <module>
    from .installation import *
  File "/mnt/gpfsA/home/t15089ki/tools/ModuleUltra/moduleultra/installation/__init__.py", line 1, in <module>
    from .pipeline_setup import *
  File "/mnt/gpfsA/home/t15089ki/tools/ModuleUltra/moduleultra/installation/pipeline_setup.py", line 6, in <module>
    from moduleultra.utils import *
  File "/mnt/gpfsA/home/t15089ki/tools/ModuleUltra/moduleultra/utils.py", line 42
    assert False, f'Could not find {filename} in {dirname} or subdirs'
                                                                     ^
SyntaxError: invalid syntax
```

My python version:
```
(py35) [t15089ki@bias5-login tools]$ python -V
Python 3.5.5
```

**Comment by dcdanko** [comment]
ModuleUltra requires > python 3.6

This is an issue with ModuleUltra not the CAP however it's a 'won't fix' either way

**Comment by kohei-108** [comment]
Thanks!
