### ISSUE TITLE
moduleultra add pipeline error.

### ISSUE THREAD

**Issue by kohei-108** [MetaSUB/MetaSUB_CAP#28]
```
(py36) [t15089ki@bias5-login ~]$ moduleultra add pipeline metasub_cap
Traceback (most recent call last):
  File "/home/t15089ki/miniconda3/envs/py36/bin/moduleultra", line 11, in <module>
    load_entry_point('ModuleUltra', 'console_scripts', 'moduleultra')()
  File "/home/t15089ki/miniconda3/envs/py36/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/t15089ki/miniconda3/envs/py36/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/t15089ki/miniconda3/envs/py36/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/t15089ki/miniconda3/envs/py36/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/t15089ki/miniconda3/envs/py36/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/t15089ki/miniconda3/envs/py36/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/mnt/gpfsA/home/t15089ki/tools/ModuleUltra/moduleultra/cli/cli.py", line 48, in addPipeline
    repo = ModuleUltraRepo.loadRepo()
  File "/mnt/gpfsA/home/t15089ki/tools/ModuleUltra/moduleultra/module_ultra_repo.py", line 132, in loadRepo
    repoPath = ModuleUltraRepo.repoDir(startDir=startDir)
  File "/mnt/gpfsA/home/t15089ki/tools/ModuleUltra/moduleultra/module_ultra_repo.py", line 127, in repoDir
    return ModuleUltraRepo.repoDir(startDir=up)
  File "/mnt/gpfsA/home/t15089ki/tools/ModuleUltra/moduleultra/module_ultra_repo.py", line 127, in repoDir
    return ModuleUltraRepo.repoDir(startDir=up)
  File "/mnt/gpfsA/home/t15089ki/tools/ModuleUltra/moduleultra/module_ultra_repo.py", line 126, in repoDir
    raise NoModuleUltraRepoFoundError()
NameError: name 'NoModuleUltraRepoFoundError' is not defined
```

My Python version: 3.6.5

**Comment by dcdanko** [comment]
Again, not an issue with the CAP. See the issue I opened in the ModuleUltra Repo for the solution.
