### ISSUE TITLE
Issue with running the CAP (missing finch or other issue?)

### ISSUE THREAD

**Issue by SiWolf** [MetaSUB/MetaSUB_CAP#37]
Hi,

I wanted to run the CAP on a test PE read dataset. Following the instructions listed on the [GitHub page](https://github.com/MetaSUB/MetaSUB_CAP#running-with-docker), I executed the following commands in order to set up the CAP using docker, but as soon as I try to run the pipeline, it crashes.

```
XXX@YYYYY:~/Downloads/test$ sudo docker run --rm -it -v /home/XXX/Downloads/db/:/home/metasub/dbs -v $PWD:/home/metasub/repo metasub/metasub_cap:latest /bin/bash -c "conda activate cap"
(base) root@c47c8ed93394:/home/metasub/repo# ls
test_read1.fastq.gz  test_read2.fastq.gz
(base) root@c47c8ed93394:/home/metasub/repo# conda activate cap
(cap) root@c47c8ed93394:/home/metasub/repo# moduleultra init
(cap) root@c47c8ed93394:/home/metasub/repo# moduleultra add pipeline metasub_cap
(cap) root@c47c8ed93394:/home/metasub/repo# datasuper add type sample microbiome
(cap) root@c89e7df87279:/home/metasub/repo# datasuper bio add-fastqs -1 _read1.fastq.gz -2 _read2.fastq.gz microbiome /home/metasub/repo/test_read1.fastq.gz /home/metasub/repo/test_read2.fastq.gz 
test: /home/metasub/repo/test_read1.fastq.gz, /home/metasub/repo/test_read2.fastq.gz
(cap) root@c47c8ed93394:/home/metasub/repo# moduleultra run -p metasub_cap -j 3 -c /home/metasub/docker_pipeline_config.py 
Running metasub_cap :: 1.0.1
subcommand "which finch" failed
/bin/sh: 1: finch: not found
subcommand "finch --version" failed
Traceback (most recent call last):
  File "/opt/conda/envs/cap/bin/moduleultra", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/envs/cap/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/cap/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/cap/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/cap/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/cap/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/envs/cap/lib/python3.6/site-packages/moduleultra/cli/cli.py", line 163, in runPipe
    benchmark=benchmark)
  File "/opt/conda/envs/cap/lib/python3.6/site-packages/moduleultra/pipeline_instance.py", line 113, in run
    custom_config_file=custom_config_file
  File "/opt/conda/envs/cap/lib/python3.6/site-packages/moduleultra/pipeline_instance.py", line 211, in preprocessConf
    customConf = openConfF(custom_config_file)
  File "/opt/conda/envs/cap/lib/python3.6/site-packages/moduleultra/pipeline_instance_utils.py", line 28, in openConfF
    pconf = openPythonConf(confF)
  File "/opt/conda/envs/cap/lib/python3.6/site-packages/moduleultra/pipeline_instance_utils.py", line 96, in openPythonConf
    __import__(importName)
  File "/root/.module_ultra_config/installed_pipelines/metasub_cap::1.0.1/docker_pipeline_config.py", line 12, in <module>
    'bt2': in_db_dir('microbes', 'staph_aureus_n315.bt2'),
TypeError: in_db_dir() takes 1 positional argument but 2 were given
```

Any ideas on what might be the issue? Was finch not included in the docker or conda environments? Also, any feedback on missing commands would be much appreciated. Thank you for your help in advance.

**Comment by dcdanko** [comment]
The finch issue is probably incidental here. It will take a few days to figure out what's going on- we'll get back to you when that's figured out.
